sonar.projectKey=alichherawalla_off-grid-mobile
sonar.organization=alichherawalla
sonar.host.url=https://sonarcloud.io

sonar.sources=src,android/app/src/main,ios
sonar.tests=__tests__,android/app/src/test,ios/OffgridMobileTests

sonar.exclusions=**/node_modules/**,**/Pods/**,**/build/**,**/coverage/**,ios/build/**,android/build/**
sonar.test.inclusions=__tests__/**,android/app/src/test/**,ios/OffgridMobileTests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
